### ISSUE TITLE
Migrate to Android X

### ISSUE THREAD

**Issue by flowhorn** [miguelpruivo/plugins_flutter_file_picker#31]
Many plugins on pub migrated to Android X. It would be very useful if the dependecies could be updated to use Android X instead of the Support Library.

**Comment by miguelpruivo** [comment]
This is already done on `beta`, can you give it a try and see if it's working for you? 

Change the dependency in the pubspec to:

```
  file_picker:
    git:
      url: https://github.com/miguelpruivo/plugins_flutter_file_picker.git
      ref: beta
```
